server:
  port: :4000
  version: 1.0
  jwtSecret: "38324-search-engine"

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: search_engine
  username: search_engine
  password: search_engine
  charset: utf8mb4

es:
  EsHost: 127.0.0.1
  EsPort: 9200
  EsIndex: mylog


redis:
  user_name: default
  address: 127.0.0.1:6379
  password:

etcd:
  address: 127.0.0.1:2379

services:
  gateway:
    name: gateway
    loadBalance: true
    addr:
      - 127.0.0.1:10001

  user:
    name: user
    loadBalance: false
    addr:
      - 127.0.0.1:10002

  favorite:
    name: favorite
    loadBalance: false
    addr:
      - 127.0.0.1:10003

  search_engine:
    name: search_engine
    loadBalance: false
    addr:
      - 127.0.0.1:10004

  mapreduce:
    name: mapreduce
    loadBalance: false
    addr:
      - 127.0.0.1:10005

SeConfig: # 改造一下，csv放到starrocks里，然后从starrock收口数据来源（读取、csv）
  Version: "1.0.0"
  StoragePath: "/Users/mac/GolandProjects/Go-SearchEngine/app/search_engine/data/db/"
  SourceWuKoFile: "./data/movies_data.csv"
  MetaPath: "/Users/mac/GolandProjects/Go-SearchEngine/app/search_engine/data/db/segments.json"
  SourceFiles:
    - "./source"
    - "./"
  MergeChannelSize:

starrocks:
  username: root
  password:
  database: test
  load_url: localhost:8083
  host: localhost
  port: 9030
  charset: utf8mb4

kafka:
  address:
    - 127.0.0.1:10000
    - 127.0.0.1:10001
    - 127.0.0.1:10002

domain:
  user:
    name: user
  favorite:
    name: favorite
  search_engine:
    name: search_engine
  mapreduce:
    name: mapreduce